services:
  api:
    build:
      context: ./api
    container_name: api
    restart: unless-stopped
    env_file:
      - .env.api
    ports:
      - "3333:3333"
    networks:
      backend-network:

  web:
    build:
      context: ./web
    container_name: web
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - .env.web
    networks:
      backend-network:
      
networks:
  backend-network:
    driver: bridge