services:
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_DATABASE=starseg
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      dev-network:
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      UPLOAD_LIMIT: 50M
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      dev-network:

volumes:
  db_data:
    driver: local

networks:
  dev-network:
    driver: bridge