services:
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-network

  api:
    build:
      context: ./api
    container_name: api
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${API_PORT}:3333"
    depends_on:
      - db
    networks:
      - backend-network

  web:
    build:
      context: ./web
    container_name: web
    restart: always
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=${SERVER_URL}:${API_PORT}
    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  db_data:
    driver: local

networks:
  backend-network: