"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const member_1 = require("../controllers/member");
const permissions_1 = require("../middlewares/permissions");
const memberRouter = express_1.default.Router();
memberRouter.get("/", member_1.getAllMembers);
memberRouter.get("/find/:id", member_1.getMember);
memberRouter.get("/filtered/:lobby", member_1.getFilteredMembers);
memberRouter.get("/count/:lobby", member_1.countMembers);
memberRouter.get("/lobby/:lobby", member_1.getMembersByLobby);
memberRouter.get("/tags/:id", member_1.getTagsByMember);
memberRouter.get("/address", member_1.getAddressTypes);
memberRouter.post("/", member_1.createMember);
memberRouter.put("/:id", member_1.updateMember);
memberRouter.delete("/:id", permissions_1.checkAdminPermission, member_1.deleteMember);
exports.default = memberRouter;
